### ISSUE TITLE
what is MD5 code

### ISSUE THREAD

**Issue by Sandy4321** [rk2900/DLF#3]
what is MD5 code in
The full dataset can be downloaded at this link and the corresponding MD5 code is 841698b0dd8718b1b4a4ff2e54bb72b4.

**Comment by rk2900** [comment]
You may check md5 code for one file through the command `md5sum filename` in Linux. That is for checking the correctness of the downloaded file content.

**Comment by Sandy4321** [comment]
And what to do for Windows

**Comment by rk2900** [comment]
> And what to do for Windows

certutil -hashfile filename MD5
